styles: Switch AppTheme to MaterialComponents
The dependency "AboutLibraries" contains a layout named
listheader_opensource.xml, which contains references to
com.google.android.material.button.MaterialButton.
That one in turn requires the base app theme to be a
descendant of `Theme.MaterialComponents`:

```
android.view.InflateException: Binary XML file line #48 in \
  com.ruesga.rview.debug:layout/listheader_opensource: \
  Binary XML file line #48 in com.ruesga.rview.debug:layout/listheader_opensource: \
  Error inflating class com.google.android.material.button.MaterialButton
Caused by: java.lang.IllegalArgumentException: \
  The style on this component requires your app theme to be \
  Theme.MaterialComponents (or a descendant).
```